### ISSUE TITLE
Drop support for node 4

### ISSUE THREAD

**Issue by jbandura** [ember-cli/eslint-plugin-ember#102]
According to ember-cli's site, the node version supported is the latest LTS, which happens to be Node 6. This probably means that we can drop support for Node 4.

**Comment by ro0gr** [comment]
@jbandura can you provide the link where ember-cli site exactly defines node support matrix please? 

I only found this one from repo:
https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md

Seems like node@4.2 is still supported.

**Comment by jbandura** [comment]
yes, you're right - I've been guiding myself by ember-best-practices plugin (which doesn't support node 4) and the LTS **recommended** section (not supported - misread that). But you're right - it's not explicilty stated that node 4 is not supported anymore - my bad.

**Comment by ro0gr** [comment]
No worries. I just was curious if there were such a statement in the cli docs.

**Comment by michalsnik** [comment]
Ok so we're holding this proposition for now and will get back to this in a while.

**Comment by bryanhickerson** [comment]
I'm wondering if we can reconsider this issue. I'm hitting a node 4 specific failure in https://github.com/ember-cli/eslint-plugin-ember/pull/239. Since the ember best practices plugin doesn't support node 4, it seems like it could be a barrier to migrating the ember best practices rules to `eslint-plugin-ember`.

**Comment by kellyselden** [comment]
As soon as April 30th hits, kill it with fire.
