### ISSUE TITLE
Can you explain to me this rule? alias-model-in-controller

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/eslint-plugin-ember#138]
I have many little, small controllers like this one:

```javascript
import Ember from 'ember';
const { alias } = Ember.computed;

export default Ember.Controller.extend({

  session: Ember.inject.service(),

  actions: {
    authenticate() {
      ....
    }
  }
....
```

and I have many errors for this rule: **alias-model-in-controller**.

Why?

I read this: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/alias-model-in-controller.md but I don't understand the reason. I don't use `model` in my controllers.

**Comment by karthiick** [comment]
@johnunclesam As of now, everything you return from route's model hook set as a `model property` in controller. We can have more meaningful property name like `people, pets` instead of model, but not without explicitly setting in setupController.

Contextual naming will be possible in routable components and this rule ensures that we avoid using the generic property name `model` in controller.

>  I have many errors for this rule: alias-model-in-controller.
I don't use model in my controllers.

This might be a bug. //cc @alexlafroscia

**Comment by jbandura** [comment]
I was actually considering the same thing a couple of days ago. I think the problem is that there's no way to actually detect whether you're using the model hook in the route to fetch anything or not.

**Comment by johnunclesam** [comment]
Detect it in the route and stop! If I'm not using model in the controller I don't need this error. No?

**Comment by timo-lindemann-victors** [comment]
I can see the general reasoning behind the rule, but it stumped me because there isn't even a route set up (meaning that I don't have a route file in that route, so the default route is set up by Ember) and I still get this error and couldn't understand what I was doing wrong. I resorted to ignoring this particular rule, but it took me a while to even understand what was happening.

**Comment by michalsnik** [comment]
No you don't need to @johnunclesam but we can't check both route and template to distinguish if you're actally using it or not. If the rule does not fit your needs then simply disable it, it's not that you have to use all rules ;)
