### ISSUE TITLE
Mixins should be included in avoid-leaking-state rule

### ISSUE THREAD

**Issue by GCheung55** [ember-cli/eslint-plugin-ember#219]
Doesn't look like Mixins are checked to see if they pass the avoid-leaking-state rule. Should they be checked?

**Comment by rwjblue** [comment]
Yes, the rule current checks anything passed to `.extend( /* this here */)`, we can check mixins but we have to be more careful about exactly how we match mixin creation.  I believe we can only match this exactly: `Mixin.create(/* this here */)` or `Ember.Mixin.create(/* this here */)` (or an import from the new modules path.

Would love a PR for this...

**Comment by jaydgruber** [comment]
@rwjblue , I'm hoping [`isEmberMixin`](https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/utils/ember.js#L257) util matches what you describe above, in which case this is a pretty simple addition. 

Only wrinkle based on looking at the `isEmberMixin` test is what to do if a native class extends Mixin. `isEmberMixin` is false for that. I think this is what we want, since arrays and objects as class fields are just fine.
