### ISSUE TITLE
Latest release added additional rules that cause a breaking change?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/eslint-plugin-ember#784]
https://github.com/NullVoxPopuli/emberclear/pull/740/checks?check_run_id=587345381

While I may be a fan of the new rules, it shouldn't break existing configs, yeah?

**Comment by bmish** [comment]
Don't worry, new recommended rules are only added in major releases (the most recent of which was [v8](https://github.com/ember-cli/eslint-plugin-ember/releases/tag/v8.0.0)).

It looks like you're seeing new violations reported because I added decorator support to some of our rules recently (specifically [require-computed-property-dependencies](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-property-dependencies.md)). Fortunately, these new violations are all autofixable.

The lack of decorator support in many of our rules is a well-documented problem and it has been one of my top priorities to address it so that we can fully support modern Ember Octane syntax. I would consider adding decorator support to existing rules to be a bug fix, and it is true that bug fixes can sometimes result in additional violations reported.

Hope that explanation helps!

**Comment by rwjblue** [comment]
>  I would consider adding decorator support to existing rules to be a bug fix, and it is true that bug fixes can sometimes result in additional violations reported.

Completely agree.
